version: "3.7"
services:
  expertise-central-front-dev:
    container_name: expertise-central-front-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
