version: "3.3"

services:
  front-end:
    build:
      context: ./packages/front-end/
      args:
        NODE_ENV: production
        REACT_APP_API: https://apps-int.bca.fr/doc-num-front/api
    depends_on:
      - back-end
    restart: always
    volumes:
      - /app/node_modules
    stdin_open: true
    networks: 
      -  app-network
    ports:
      - "3333:3333"

  back-end:
    environment:
      - API_PREVIEW=https://apps-int.bca.fr/doc-num-front/api
      - API_DOC_NUM=https://apps-int.bca.fr/doc-num/api/v1
      - API_AUTH=https://int4.bca.fr/authentication/api/v1
      - API_BCA_SIGN=http://s00i105i.bcaexpertise.org:4327/bca-sign/v1/BCAGDOC
      - API_MULSOFT=https://bca-e-api-xps-b2b-int.de-c1.cloudhub.io/api/v1
      - API_MULSOFT_BASIC=YWRtaW46YWRtaW4=
      - PATH_TMP=/app/tmp/
      - NAMESPACE=/doc-num-front/api
      - WKHTMLTOIMAGE=xvfb-run -a -s '-screen 0 1024x768x30' wkhtmltoimage
    build:
      context: ./packages/back-end/
      args:
        DATABASE_URL: postgresql://BCAGDOC:BCAGDOCPASS@PSQL_DEV_1.bcaexpertise.org:5447/bcagdoc?schema=public
    ports:
      - "6001:3500"
    networks: 
      -  app-network
    restart: always
    volumes:
      - /app/node_modules
      - /app/tmp

networks: 
  app-network:
    external: true
